name: Smarthome
description: Steuerung Ihres Zuhauses
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.6
  http: ^0.13.3
  flutter_redux: ^0.8.2
  nfc_manager: ^3.1.0
  curved_navigation_bar: ^1.0.1
  wave: ^0.2.0
  weather_icons: ^3.0.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2
  yaml: ^3.1.0
  flutter_inappwebview: ^5.3.2
  cyclop: ^0.4.1
  x509: ^0.2.2
  asn1lib: ^1.0.2
  basic_utils: ^3.6.1
  fluttertoast: ^8.0.8
  encrypted_shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/raleway-600.ttf
    - assets/fonts/raleway-700.ttf
    - assets/fonts/raleway-regular.ttf
    - assets/images/icon_inverted.png
    - assets/images/icons8_NFC_N_96px.png
    - pubspec.yaml
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway-regular.ttf
        - asset: assets/fonts/raleway-600.ttf
          weight: 600
        - asset: assets/fonts/raleway-700.ttf
          weight: 700
