name: Flutter

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build_apk:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: "zulu"
        java-version: "11"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "2.10.0"

    - name: Load dependencies
      working-directory: ./src/app/smarthome
      run: flutter pub get

    - name: Build APK
      working-directory: ./src/app/smarthome
      run: flutter build apk

    - name: Build web
      working-directory: ./src/app/smarthome
      run: flutter build web
